services:
  api:
    build: .
    container_name: inkomoko-api
    restart: unless-stopped
    expose:
      - "4000"
    environment:
      - PORT=4000
    networks:
      - inkomoko-network

  nginx:
    image: nginx:alpine
    container_name: inkomoko-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - inkomoko-network

networks:
  inkomoko-network:
    driver: bridge
